# Generated by Django 5.1.7 on 2025-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_module', '0003_alter_event_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
