# Generated by Django 5.1.7 on 2025-04-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_module', '0007_eventparticipants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
