# Generated by Django 5.1.7 on 2025-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_module', '0009_event_participants_delete_eventparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
